controllers/DevlogController.php
<?php

namespace app\controllers;

use Yii;
use app\models\users;
use app\models\posts;
use yii\data\Pagination;

use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;

/**
 * DevlogController implements the CRUD actions for posts model.
 */
class DevlogController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'], // auth-user
                    ],
                    [
                        'allow' => true,
                        'actions' => ['index', 'view'], // only
                        'roles' => ['?'], // guest-user
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all posts models.
     * @return mixed
     */
    public function actionIndex()
    {
        /*
            aksi ":joinWith()" akan eksekusi aksi ":getUsers()"
            pada model "Posts"
        */

        $query = Posts::find()
            ->where($this->request->get('search', []))
            ->orderBy([
                'created' => SORT_DESC,
                'head' => SORT_ASC,
            ])
            ->joinWith('users');
        $count = $query->count();

        $pagination = new Pagination([
            'totalCount' => $count,
            'pageSize' => 10,
        ]);

        $list = $query
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        return $this->render('index', [
            'list' => $list,
        ]);
    }

    /**
     * Displays a single posts model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new posts model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Posts();
        $model->by = Yii::$app->user->id;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->pk]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing posts model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->pk]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing posts model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the posts model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return posts the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = posts::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/devlog/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use skeeks\yii2\ckeditor\CKEditorWidget;
use skeeks\yii2\ckeditor\CKEditorPresets;

/* @var $this yii\web\View */
/* @var $model app\models\posts */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="posts-form">
    <?php $form = ActiveForm::begin(); ?>

    <?= $form
        ->field($model, 'head')
        ->label('Judul')
        ->textInput(['maxlength' => true])
        ?>

    <?= $form
    	->field($model, 'body')
        ->label('Isian')
    	->textarea(['rows' => 7])
    	->widget(CKEditorWidget::class, [
    		'preset' => CKEditorPresets::BASIC,
    	])
        ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>

views/devlog/create.php
<?php
/* @var $this yii\web\View */
/* @var $model app\models\posts */

$this->title = 'Create';
$this->params['breadcrumbs'][] = ['label' => 'DevLog', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="posts-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/devlog/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;

/* @var $this yii\web\View */

$this->title = 'Index';
$this->params['breadcrumbs'][] = ['label' => 'DevLog', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="posts-index">
    <?php foreach ($list as $item):
        $href_view = Url::toRoute(['devlog/view', 'id' => $item->pk]);
        $item_name = $item->users->name ?? $item->users->usr;
        $href_name = Url::toRoute(['index', 'search[by]' => $item->users->id]);
        $item_created = $item->created;
        $item_created = Yii::$app->formatter->asDatetime($item_created);
        ?>
        <h1><a href="<?= $href_view ?>"><?= Html::encode($item->head) ?></a></h1>
        <p>
            Oleh
            <?= Html::a($item_name, $href_name) ?>
            Pada <?= $item_created ?>
        </p>
    <?php endforeach ?>
</div>

views/devlog/update.php
<?php
/* @var $this yii\web\View */
/* @var $model app\models\posts */

$this->title = 'Update: ' . ($model->head ?? $model->pk);
$this->params['breadcrumbs'][] = ['label' => 'DevLog', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->head ?? $model->pk, 'url' => ['view', 'id' => $model->pk]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="posts-update">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/devlog/view.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\posts */

// paksa IDE untuk bisa deteksi datatype (bukan hal penting).
$model = (fn():\app\models\Posts => $model)();

$item_name = $model->users->name ?? $model->users->usr;
$href_name = Url::toRoute(['index', 'search[by]' => $model->users->id]);

$item_created = $model->created;
$item_created = Yii::$app->formatter->asDatetime($item_created);

$this->title = $model->head;
$this->params['breadcrumbs'][] = ['label' => 'DevLog', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'View';
\yii\web\YiiAsset::register($this);
?>
<div class="posts-view">

    <h1><?= Html::encode($model->head) ?></h1>

    <p>
        Oleh
        <?= Html::a($item_name, $href_name) ?>
        Pada <?= $item_created ?>
    </p>

    <article><?= $model->body ?></article>

    <?php if (!Yii::$app->user->isGuest): ?>
        <p>
            <?= Html::a('Update', ['update', 'id' => $model->pk], ['class' => 'btn btn-primary']) ?>
            <?= Html::a('Delete', ['delete', 'id' => $model->pk], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => 'Are you sure you want to delete this item?',
                    'method' => 'post',
                ],
            ]) ?>
        </p>
    <?php endif ?>
</div>